Exploratory notebook
networkx/outreachy pull request #171
Opened 2023-03-14 13:06 UTC by devotuoma

I have created an exploratory notebook for a random Erdos-any graph using 100 nodes and 0.3 edge probability and 0.6 edge probability. I have also created a barabasi_albert_graph and given inferences about the plots in the markdown. I accept comments and any recommendations.

2023-03-14 16:39 UTC, paulitapb commented on 2023-round-1/devotuoma/nx_tutorial_script.py
> +NetworkX, nodes can be any hashable object such as text string, an image, an XML object, another Graph, a customized node object, etc.
```suggestion
#NetworkX, nodes can be any hashable object such as text string, an image, an XML object, another Graph, a customized node object, etc.
```

2023-03-14 16:39 UTC, paulitapb commented on 2023-round-1/devotuoma/nx_tutorial_script.py
> +nx.draw_networkx(G,with_labels=True,node_color=colors)
The list colors have a different length than the number of nodes in G. The list was created using the nodes of the first digraph G that have fewer nodes than the Petersen graph.

2023-03-14 16:39 UTC, paulitapb commented on 2023-round-1/devotuoma/nx_tutorial_script.py
> +import matplotlib.pyplot as plt
This should be before you use `plt.subplot()` in line 46. Preferably all imports at the beginning of the file.

2023-03-14 16:39 UTC, paulitapb commented on 2023-round-1/devotuoma/nx_tutorial_script.py
> +G.add_node(1, group='int',color='red')
Here you add node 1 twice. The resulting graph will not have 2 nodes labeled "1" but with different attributes.

2023-03-14 19:39 UTC, paulitapb requested changes
Just check the comments on the tutorial script

2023-03-15 12:32 UTC, devotuoma commented
Okay am correcting this

2023-03-18 13:04 UTC, MridulS commented
I merged https://github.com/networkx/outreachy/pull/148 so closing this. It's a duplicate

2023-03-18 13:04 UTC, closed without merging